apiVersion: view.littlewat.github.io/v1
kind: MarkdownView
metadata:
  name: markdownview-sample
spec:
  markdowns:
    SUMMARY.md: |
      # Summary

      - [Page1](page1.md)
      - [Page2](page2.md)

    page1.md: |
      # Page 1

      - 1ページ目のコンテンツですばい。
    page2.md: |
      # Page 2

      - 2ページ目のコンテンツですばい。
      - hogehoge
  replicas: 1
  viewerImage: "peaceiris/mdbook:latest"
